// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRUsoNbGNp8G0OCfbIeODaO0lQjOihg3c',
    appId: '1:125797901924:web:6003c4c047a854b4e12171',
    messagingSenderId: '125797901924',
    projectId: 'papeleria-cometa',
    authDomain: 'papeleria-cometa.firebaseapp.com',
    storageBucket: 'papeleria-cometa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpGifDSPwi2Jte9CpYNuphcSQ59jnGDV4',
    appId: '1:125797901924:android:805620d4ebfb85e2e12171',
    messagingSenderId: '125797901924',
    projectId: 'papeleria-cometa',
    storageBucket: 'papeleria-cometa.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiJQhRw7TJgic296kE_7IATStFnb1IVng',
    appId: '1:125797901924:ios:5002646823c18857e12171',
    messagingSenderId: '125797901924',
    projectId: 'papeleria-cometa',
    storageBucket: 'papeleria-cometa.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiJQhRw7TJgic296kE_7IATStFnb1IVng',
    appId: '1:125797901924:ios:5002646823c18857e12171',
    messagingSenderId: '125797901924',
    projectId: 'papeleria-cometa',
    storageBucket: 'papeleria-cometa.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRUsoNbGNp8G0OCfbIeODaO0lQjOihg3c',
    appId: '1:125797901924:web:ac32ca6fb390885ce12171',
    messagingSenderId: '125797901924',
    projectId: 'papeleria-cometa',
    authDomain: 'papeleria-cometa.firebaseapp.com',
    storageBucket: 'papeleria-cometa.firebasestorage.app',
  );

}